/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bot: typeof import('./components/bot.md')['default']
    ChatmailMd: typeof import('./components/chatmail-md.md')['default']
    Dc: typeof import('./components/dc.md')['default']
    DcFeaturesMd: typeof import('./components/dc-features-md.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityContent: typeof import('./components/security-content.md')['default']
    Slide: typeof import('./components/slide.vue')['default']
    Slide2sides: typeof import('./components/slide2sides.vue')['default']
    Webxdc_content: typeof import('./components/webxdc_content.md')['default']
  }
}
