/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/bots': RouteRecordInfo<'/bots', '/bots', Record<never, never>, Record<never, never>>,
    '/chatmail': RouteRecordInfo<'/chatmail', '/chatmail', Record<never, never>, Record<never, never>>,
    '/dc-features': RouteRecordInfo<'/dc-features', '/dc-features', Record<never, never>, Record<never, never>>,
    '/deltachat': RouteRecordInfo<'/deltachat', '/deltachat', Record<never, never>, Record<never, never>>,
    '/instant-onboarding': RouteRecordInfo<'/instant-onboarding', '/instant-onboarding', Record<never, never>, Record<never, never>>,
    '/intro': RouteRecordInfo<'/intro', '/intro', Record<never, never>, Record<never, never>>,
    '/outro': RouteRecordInfo<'/outro', '/outro', Record<never, never>, Record<never, never>>,
    '/structure': RouteRecordInfo<'/structure', '/structure', Record<never, never>, Record<never, never>>,
    '/webxdc': RouteRecordInfo<'/webxdc', '/webxdc', Record<never, never>, Record<never, never>>,
  }
}
